### ISSUE TITLE
Can't use ES6 import/export

### ISSUE THREAD

**Issue by dittmarconsulting** [graphboss/aws-sam-webpack-plugin#54]
Hi there,

I had high hopes when I found that plugin because I wanted to develop my NodeJs Lambda's using the ES6 syntax.

I followed all the steps described in the [README.md](https://github.com/graphboss/aws-sam-webpack-plugin#usage-with-babel) under the `Usage with Babel` section.

After I completed the setup I can successfully build and run the app in Docker by invoking `sam local invoke ` with this demo handler:

```javascript
exports.helloFromLambdaHandler = async (event, context) => {
  try {
    response = {
      statusCode: 200,
      body: JSON.stringify({
        message: "hello world",
      }),
    };
  } catch (err) {
    console.log(err);
    return err;
  }
  return response;
};
```

which gives me the expected output

```javascript
START RequestId: 6c8eca3c-36ee-4dac-8e0e-fffb00f1d256 Version: $LATEST
END RequestId: 6c8eca3c-36ee-4dac-8e0e-fffb00f1d256
REPORT RequestId: 6c8eca3c-36ee-4dac-8e0e-fffb00f1d256	Init Duration: 0.33 ms	Duration: 172.13 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
{"statusCode":200,"body":"{\"message\":\"hello world\"}"}% 
```

but as soon I refactor the handler like that

```javascript
export const helloFromLambdaHandler = async (event, context) => {
  try {
    response = {
      statusCode: 200,
      body: JSON.stringify({
        message: "hello world",
      }),
    };
  } catch (err) {
    console.log(err);
    return err;
  }
  return response;
};
```

I get this response

```javascript
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token 'export'",
    "stack": ["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token 'export'", "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)", "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)", "    at Object.<anonymous> (/var/runtime/index.js:43:30)", "    at Module._compile (internal/modules/cjs/loader.js:1063:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)", "    at Module.load (internal/modules/cjs/loader.js:928:32)", "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)", "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)", "    at internal/main/run_main_module.js:17:47"]
}
```

Which means that Babel didn't compile the code back to ES5 I guess?

Here the content of `babel.config.js`

```javascript
module.exports = {
  plugins: [
    "@babel/proposal-class-properties",
    [
      "@babel/plugin-transform-runtime",
      {
        regenerator: true,
      },
    ],
  ],
  presets: ["@babel/env", "@babel/typescript"],
};
```

and the content of my `package.json`

```javascript
{
  "name": "demo",
  "description": "demo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "test": "jest",
    "build": "webpack-cli",
    "clean": "rimraf .aws-sam .vscode",
    "prebuild": "rimraf .aws-sam .vscode",
    "prewatch": "rimraf .aws-sam .vscode",
    "watch": "webpack-cli -w"
  },
  "dependencies": {
    "@babel/runtime": "^7.13.10",
    "aws-sdk": "^2.863.0",
    "mysql": "^2.18.1",
    "source-map-support": "^0.5.19"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.10",
    "@babel/core": "^7.13.10",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-transform-runtime": "^7.13.10",
    "@babel/preset-env": "^7.13.10",
    "@babel/preset-typescript": "^7.13.0",
    "aws-sam-webpack-plugin": "^0.9.0",
    "babel-loader": "^8.2.2",
    "jest": "^26.6.3",
    "webpack": "^5.25.0",
    "webpack-cli": "^4.5.0"
  }
}
```

**Comment by dittmarconsulting** [comment]
Changed the function body

**Comment by ryansonshine** [comment]
@dittmarconsulting can you share how you're referencing the function in your `template.yaml`?

**Comment by buggy** [comment]
The mostly likely reason is a change in the way SAM locates the template file. If your template is named `template.yml` then rename it to `template.yaml` or upgrade to 0.10.0 when it's released.
